# Local development only

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

app.cors.allowed-origin=https://portal.partner-forex.com
