spring.application.name=card-management

# H2 Database
spring.datasource.url=jdbc:h2:mem:carddb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# H2 Console
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:5556/dex