spring.application.name=card-management

# PostgreSQL Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false


# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH2_ISSUER_URI}

# Swagger / OpenAPI disabled by default
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Error response hardening
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never

app.cors.allowed-origin=https://portal.partner-forex.com
